 use Internet_Cafe

CREATE TABLE Employee(
eid INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Salary INT,
Age INT CHECK(Age > 16 AND Age < 50))

CREATE TABLE Booth(
bid INT PRIMARY KEY,
eid INT FOREIGN KEY REFERENCES Employee(eid))

CREATE TABLE Category(
CategoryId INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL)

CREATE TABLE Product(
pid INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
CategoryId INT FOREIGN KEY REFERENCES Category(CategoryId),
Price INT CHECK (Price > 0 AND Price < 100))

CREATE TABLE PC(
pcid INT PRIMARY KEY,
PricePerH INT CHECK(PricePerH > 0 AND PricePerH < 50))

CREATE TABLE Customer(
cid INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
pcid INT FOREIGN KEY REFERENCES PC(pcid),
bid INT FOREIGN KEY REFERENCES Booth(bid))

CREATE TABLE OrderFromC(
oid INT PRIMARY KEY,
cid INT FOREIGN KEY REFERENCES Customer(cid))

CREATE TABLE TransactionDetails(
oid INT FOREIGN KEY REFERENCES OrderFromC(oid),
pid INT FOREIGN KEY REFERENCES Product(pid),
noOfP INT CHECK(noOfP > 0),
CONSTRAINT pk_TransactionDetails PRIMARY KEY(oid, pid))

CREATE TABLE ITGuy(
itid INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Salary INT)

CREATE TABLE PCCheck(
checkId INT PRIMARY KEY,
itid INT FOREIGN KEY REFERENCES ITGuy(itid),
pcid INT FOREIGN KEY REFERENCES PC(pcid),
ok VARCHAR(5) NOT NULL)